#!/usr/bin/env bash
#This is a comment
filename="/etc/passwd"

while IFS=':' read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$filename"
