#!/usr/bin/env bash
#This is a comment
hour=0
minute=0
count=1

while [ $count -le 70 ]
do
    if [ $minute -eq 0 ]
    then
        echo "Hour: $hour"
    fi
    echo $minute

    minute=$((minute+1))
    if [ $minute -eq 60 ]
    then
        hour=$((hour+1))
        minute=0
    fi
    count=$((count+1))
done
