#!/usr/bin/env bash
# Trap signals and handle them appropriately
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit 0" SIGQUIT SIGTERM

# Get the current process ID (PID) and save it to the file
echo $$ > /var/run/myscript.pid

# Display the message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done
